nzo_encryptor:
    secret_key: '7134743677397A24432646294A404E63'    # Required, max length of 100 characters.
    secret_iv:  'manosteo2021'                                    # Required only if "random_pseudo_bytes" is FALSE. Max length of 100 characters.
    cipher_algorithm: 'aes-128-ctr'                              # optional, default: 'aes-256-ctr'
    # base64_encode:                                  # optional, default: TRUE
    # format_base64_output:                           # optional, default: TRUE, used only when 'base64_encode' is set to TRUE
    random_pseudo_bytes: TRUE                           # optional, default: TRUE (generate a random encrypted text output each time => MORE SECURE !)